### PR TITLE
Need to merge "Merge1.1.x" to "master"

### PR DESCRIPTION
**Pull request by Kesim**
This branch is from 

> 1.0.x

that is made by @ShimGyurim .

Check this code one more and merge to master.

### CODE REVIEW

**Comment by ShimGyurim** [comment]
This branch is not set korean yet. I don't know result of this merge.

**Comment by Kesim** [comment]
image
No. This branch is already updated. So we need to check only other side.

**Review by ShimGyurim — COMMENTED** [review]
OK. nothing special

**Review by ShimGyurim — APPROVED** [review]
OK. got it

**Pull request merged**
